### ISSUE TITLE
Can't attach assets to a page after filtering

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-clipped-extension#9]
When attaching assets to a page in Trusty, the asset icons usually show Insert or Attach options. If the asset is a pdf, it only shows Edit or Remove options.

To repro:
1) Go to a page in Trusty
2) Click the "assets" text at the bottom of the page to attach an asset.
3) In the assets modal window, mouse over an image-- Insert or Attach options display 
4) Now either click the pdf tab or upload a pdf and mouse over the asset--Edit or Remove display.

There isn't a clear way of attaching pdfs to pages. It can be done manually, but it's kind of wonky.

**Comment by sipple** [comment]
Updating the title of this to match what we've discovered the problem is: Any filtering or searching in the asset popup removes the insert button and replaces it with edit. This is due to the ajax call returning the same partial as it would on the main asset page. We'll need a switch to change this to insert from edit in these cases.
